name: Demo_app_grocery
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.4+32

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0
  carousel_pro: ^0.0.13
  gradient_app_bar: ^0.0.1
  gradient_bottom_navigation_bar: ^1.0.0+4
  flutter_staggered_grid_view: "^0.2.7"
  bmnav: ^0.3.4
  flutter_rating: ^0.0.2
  url_launcher: ^5.0.2
  smooth_star_rating: 1.0.3
  smiley_rating_dialog: ^0.0.1
  store_redirect: 1.0.2
  flutter_launcher_icons:


  # For information on the generic Dart part of this file, see the
  # following page: https://www.dartlang.org/tools/pub/pubspec
  cupertino_icons: ^0.1.3
  pin_entry_text_field: ^0.1.3
  pin_input_text_field: ^0.2.1
  pinput: ^0.1.6
  shared_preferences: ^0.5.1+2
  flutter_swiper: ^1.1.6
  badges: ^0.0.6
  connectivity: ^0.4.4
  flushbar: 1.10.4
  intl: 0.16.1
  package_info: 0.4.0+14
flutter_icons:
  image_path: "assets/Grocery final icon.jpg"
  android: true
  ios: true
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.jpg
    - assets/Screenshot_20200718-071421 (2).png
    - assets/Screenshot_20200718-071421 (3).png
    - assets/Screenshot_20200718-071421.png
    - assets/images/otp.png
    - assets/images/banner1.jpeg
    - assets/images/icons/footer_dashboard.png
    - assets/images/icons/footer_offers.png
    - assets/images/icons/footer_invite.png
    - assets/images/icons/footer_resale.png
    - assets/images/restaurant.png
    - assets/images/vegetables.png
    - assets/images/grocery.png
    - assets/images/non-veg.png
    - assets/images/promo.png
    - assets/images/icon_like.png
    - assets/images/icon_like_added.png
    - assets/images/mobile_icon.jpg
    - assets/images/icon_rating.png
    - assets/images/icon_rating_half.png
    - assets/images/icon_rating-dark.png
    - assets/images/icon_oniline_order.png
    - assets/images/icon_ecommerce.png
    - assets/images/icons/footer_social.png
    - assets/images/icons/footer_logo.png
    - assets/images/icons/header_cart.png
    - assets/images/icons/header_search.png
    - assets/images/icons/header_like.png
    - assets/images/icons/header_notification.png
    - assets/images/icons/icon_call_now.png
    - assets/images/icons/update_profile_cion.png
    - assets/images/icons/offer.png
    - assets/images/icons/maintaince_module_icon.png
    - assets/images/directory.png
    - assets/images/medical.png
    - assets/images/favorite-1.png
    - assets/images/favorite-2.png
    - assets/images/icon_send.png
    - assets/images/gallery_img.png
    - assets/images/13B-map.png
    - assets/images/offers.jpg
    - assets/images/profile_icon.jpg
    - assets/images/icons/societ_icon.jpg
    - assets/images/plus.jpg
    - assets/images/minus.jpg
    - assets/images/delete.png
    - assets/ic_launcher.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages